const loginActionTypes = {
  RESET_FORM_ALERT_BOXES: 'RESET_FORM_ALERT_BOXES',
  SET_FORM_FIELD: 'SET_FORM_FIELD',
  LOGGING_IN: 'LOGGING_IN',
  BASIC_LOGIN_SUCCEED: 'BASIC_LOGIN_SUCCEED',
  BASIC_LOGIN_FAIL: 'BASIC_LOGIN_FAIL',
};

export default loginActionTypes;
