const paymentActionTypes = {
  SET_FORM_FIELD: 'SET_FORM_FIELD',
  PAYING: 'PAYING',
  PAYMENT_SUCCEED: 'PAYMENT_SUCCEED',
  ALREADY_PAID: 'ALREADY_PAID',
  NOT_ELIGIBLE_FOR_REFERRAL_DISCOUNT: 'NOT_ELIGIBLE_FOR_REFERRAL_DISCOUNT',
  REFERRAL_CODE_NOT_FOUND: 'REFERRAL_CODE_NOT_FOUND',
  PAYMENT_FAIL: 'PAYMENT_FAIL',
};

export default paymentActionTypes;
