const referralFormActionTypes = {
  RESET_FORM_ALERT_BOXES: 'RESET_FORM_ALERT_BOXES',
  REDEEMING_CREDITS: 'REDEEMING_CREDITS',
  REDEEM_CREDITS_SUCCEED: 'REDEEM_CREDITS_SUCCEED',
  REDEEM_CREDITS_FAIL: 'REDEEM_CREDITS_FAIL',
};

export default referralFormActionTypes;
