const shareSectionActionTypes = {
  OPENING_MODAL: 'OPENING_MODAL',
  CLOSING_MODAL: 'CLOSING_MODAL',
  SENDING_EMAIL_TO_REFERRAL: 'SENDING_EMAIL_TO_REFERRAL',
  SEND_EMAIL_TO_REFERRAL_SUCCEED: 'SEND_EMAIL_TO_REFERRAL_SUCCEED',
  SEND_EMAIL_TO_REFERRAL_FAIL: 'SEND_EMAIL_TO_REFERRAL_FAIL',
};

export default shareSectionActionTypes;
