const forgotPasswordActionTypes = {
  RESET_FORM_ALERT_BOXES: 'RESET_FORM_ALERT_BOXES',
  SET_FORM_FIELD: 'SET_FORM_FIELD',
  RESETTING_PASSWORD: 'RESETTING_PASSWORD',
  RESET_PASSWORD_SUCCEED: 'RESET_PASSWORD_SUCCEED',
  RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
};

export default forgotPasswordActionTypes;
