const signupFormActionTypes = {
  SET_FORM_FIELD: 'SET_FORM_FIELD',
  SIGNING_UP: 'SIGNING_UP',
  SIGNUP_SUCCEED: 'SIGNUP_SUCCEED',
  EMAIL_ALREADY_SIGNUP: 'EMAIL_ALREADY_SIGNUP',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
};

export default signupFormActionTypes;
