const authActionTypes = {
  USER_INFO_SYNC: 'USER_INFO_SYNC',

  IS_LOGGED_IN: 'IS_LOGGED_IN',
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  AUTH_CHECK_FAIL: 'AUTH_CHECK_FAIL',

  LOGOUT_SUCCEED: 'LOGOUT_SUCCEED',
  LOGOUT_FAIL: 'LOGOUT_FAIL',

  SIGNUP_SUCCEED: 'SIGNUP_SUCCEED',
  BASIC_LOGIN_SUCCEED: 'BASIC_LOGIN_SUCCEED',
};

export default authActionTypes;
