const accountActionTypes = {
  SET_ACCOUNT_FORM_FIELD: 'SET_ACCOUNT_FORM_FIELD',
  RESET_ACCOUNT_FORM: 'RESET_ACCOUNT_FORM',
  UPDATING_PROFILE: 'UPDATING_PROFILE',
  UPDATE_PROFILE_SUCCEED: 'UPDATE_PROFILE_SUCCEED',
  UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',

  CANCELLING_SUBSCRIPTION: 'CANCELLING_SUBSCRIPTION',
  CANCEL_SUBSCRIPTION_SUCCEED: 'CANCEL_SUBSCRIPTION_SUCCEED',
  CANCEL_SUBSCRIPTION_FAIL: 'CANCEL_SUBSCRIPTION_FAIL',
};

export default accountActionTypes;
