const accountActionTypes = {
  SET_FORM_FIELD: 'SET_FORM_FIELD',
  UPDATING_PROFILE: 'UPDATING_PROFILE',
  UPDATE_PROFILE_SUCCEED: 'UPDATE_PROFILE_SUCCEED',
  UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',
  
  CANCELLING_SUBSCRIPTION: 'CANCELLING_SUBSCRIPTION',
  CANCEL_SUBSCRIPTION_SUCCEED: 'CANCEL_SUBSCRIPTION_SUCCEED',
  CANCEL_SUBSCRIPTION_FAIL: 'CANCEL_SUBSCRIPTION_FAIL',
};

export default accountActionTypes;
