const forgotPasswordConstants = {
  SET_FORGOT_PASSWORD_FORM_FIELD: 'SET_EMAIL_TO_RESET',
  RESETTING_PASSWORD: 'RESETTING_PASSWORD',
  RESET_PASSWORD_SUCCEED: 'RESET_PASSWORD_SUCCEED',
  RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
};


export default forgotPasswordConstants;
