const accountProfileActionTypes = {
  SET_FORM_FIELD: 'SET_FORM_FIELD',
  RESET_FORM: 'RESET_FORM',
  UPDATING_PROFILE: 'UPDATING_PROFILE',
  UPDATE_PROFILE_SUCCEED: 'UPDATE_PROFILE_SUCCEED',
  UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',
};

export default accountProfileActionTypes;
