const accountSubscriptionActionTypes = {
  CANCELLING_SUBSCRIPTION: 'CANCELLING_SUBSCRIPTION',
  CANCEL_SUBSCRIPTION_SUCCEED: 'CANCEL_SUBSCRIPTION_SUCCEED',
  CANCEL_SUBSCRIPTION_FAIL: 'CANCEL_SUBSCRIPTION_FAIL',
};

export default accountSubscriptionActionTypes;
